name: ci
on:
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ main, release ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0 # TODO: remove this when we cache the builds

jobs:
  ci:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      run: rustup update

    - name: build
      run: cargo build --all --release

    - name: test
      run: |
        cargo test --release --all-targets

        #cd file-tree-merge/tests/scripts
        #sh tests.sh
      shell: bash

    - name: Set file extension
      id: set_ext
      run: echo "ext=$(if [[ '${{ matrix.runner }}' == windows* ]]; then echo '.exe'; else echo ''; fi)" >> $GITHUB_ENV

    - name: upload binary
      if: ! startsWith(matrix.runner, 'windows')
      uses: actions/upload-artifact@v4
      with:
        name: syncoxiders_${{ matrix.runner }}
        path: target/release/syncoxiders

    - name: upload binary
      if: startsWith(matrix.runner, 'windows')
      uses: actions/upload-artifact@v4
      with:
        name: syncoxiders_${{ matrix.runner }}
        path: target/release/syncoxiders.exe